"""
OrchestrAI - Reports API Router
"""
import uuid
import json
from fastapi import APIRouter, HTTPException, Depends
from models.schemas import ReportCreate
from core.security import get_current_user, require_manager
from core.database import get_db
from agents.orchestrator import get_orchestrator
import asyncio
from services.email_service import send_email_notification

router = APIRouter(prefix="/api/reports", tags=["Reports"])


@router.get("")
async def list_reports(current_user: dict = Depends(get_current_user)):
    """List all reports."""
    db = get_db()
    result = db.table("reports").select("*").order("created_at", desc=True).execute()
    reports = []
    for r in result.data:
        if isinstance(r.get("content"), str):
            try:
                r["content"] = json.loads(r["content"])
            except:
                r["content"] = {}
        reports.append(r)
    return reports


@router.post("")
async def generate_report(req: ReportCreate, current_user: dict = Depends(require_manager)):
    """Generate a new AI-powered report."""
    db = get_db()
    orchestrator = get_orchestrator()

    # Gather report data
    report_data = {"report_type": req.report_type.value}

    if req.project_id:
        proj = db.table("projects").select("*").eq("id", req.project_id).execute()
        if proj.data:
            report_data["project_name"] = proj.data[0]["name"]
        tasks = db.table("tasks").select("*").eq("project_id", req.project_id).execute()
        report_data["tasks"] = tasks.data
    
    if req.team_id:
        team = db.table("teams").select("*").eq("id", req.team_id).execute()
        if team.data:
            report_data["team_name"] = team.data[0]["name"]
        
        # Get team feedback
        feedback = db.table("feedback").select("*").eq("project_id", req.project_id or "").execute()
        report_data["feedback"] = feedback.data

    # Get performance data
    if req.project_id:
        perf = db.table("performance").select("*").eq("project_id", req.project_id).execute()
        report_data["performance"] = perf.data

    # Generate report with AI
    ai_report = await orchestrator.generate_report(report_data, req.report_type.value)

    report_id = str(uuid.uuid4())
    db.table("reports").insert({
        "id": report_id,
        "title": req.title or ai_report.get("title", f"{req.report_type.value.capitalize()} Report"),
        "report_type": req.report_type.value,
        "project_id": req.project_id or "",
        "team_id": req.team_id or "",
        "generated_by": current_user["sub"],
        "content": json.dumps(ai_report),
        "summary": ai_report.get("executive_summary", ""),
        "period_start": req.period_start or None,
        "period_end": req.period_end or None,
    }).execute()
    
    # Send Email to Manager
    manager_res = db.table("users").select("email, full_name").eq("id", current_user["sub"]).execute()
    if manager_res.data:
        mgr = manager_res.data[0]
        asyncio.create_task(send_email_notification(
            to_email=mgr["email"],
            subject=f"New Report Generated: {req.report_type.value.capitalize()} Report",
            body=f"Hello {mgr['full_name']},\n\nYour {req.report_type.value} report has been successfully generated by OrchestrAI.\n\nSummary:\n{ai_report.get('executive_summary', 'View dashboard for details.')}\n\nPlease check your OrchestrAI dashboard to view or download the full PDF."
        ))

    return {
        "id": report_id,
        "report": ai_report,
        "message": "Report generated successfully"
    }


@router.get("/{report_id}")
async def get_report(report_id: str, current_user: dict = Depends(get_current_user)):
    """Get report details."""
    db = get_db()
    result = db.table("reports").select("*").eq("id", report_id).execute()
    if not result.data:
        raise HTTPException(status_code=404, detail="Report not found")
    
    report = result.data[0]
    if isinstance(report.get("content"), str):
        try:
            report["content"] = json.loads(report["content"])
        except:
            report["content"] = {}
    return report
